# This is a basic workflow to help you get started with Actions

name: Project Sciagatta

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ project_sciagatta ]
  pull_request:
    branches: [ project_sciagatta ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Builds all major OS versions of FA
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out the code
      uses: actions/checkout@v2.3.4
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      
    - name: npm install and build
      run: |
        npm install
        npm run build
    
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: oppifjellet@gmail.com
        build_dir: dist/spa
    