# This is a basic workflow that is manually triggered

name: Build App

# Manually triggered
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the application being built'
        required: true

jobs:

  # Builds all major OS versions of FA
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out the code
      uses: actions/checkout@v2.3.4

      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      
    - name: npm install and build
      run: |
        npm install
        npm run build
    
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: oppifjellet@gmail.com
        build_dir: dist/spa
    
